name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Permissions
        run: chmod +w /backend.js

      - name: Inject API Key
        run: |
          echo "window.FIREBASEAPIKEY = '${{ secrets.FIREBASEAPIKEY }}';" > /backend.js
        env:
          FIREBASEAPIKEY: ${{ secrets.FIREBASEAPIKEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /
